name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
          matrix:
            NODE_VERSION: ['8', '10', '12', '13']
            VARIANT: [ 'buster', 'buster-slim', 'stretch', 'stretch-slim']

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        git clone https://github.com/bats-core/bats-core.git
        cd bats-core
        sudo ./install.sh /usr/local
        cd ..
        ./test-build.sh ${{ matrix.NODE_VERSION }} ${{ matrix.VARIANT }}
